// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJesckhL14wEZTzhc8dg2hge0KaVt8LQ',
    appId: '1:385557618478:android:7bcd60c7751d11bdee64bf',
    messagingSenderId: '385557618478',
    projectId: 'shoplist-dev-da28c',
    storageBucket: 'shoplist-dev-da28c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6YuCRmm2l444mpULxPntsSXfwImKXvyU',
    appId: '1:385557618478:ios:feb40f2930589332ee64bf',
    messagingSenderId: '385557618478',
    projectId: 'shoplist-dev-da28c',
    storageBucket: 'shoplist-dev-da28c.firebasestorage.app',
    iosBundleId: 'com.example.shoplist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6YuCRmm2l444mpULxPntsSXfwImKXvyU',
    appId: '1:385557618478:ios:feb40f2930589332ee64bf',
    messagingSenderId: '385557618478',
    projectId: 'shoplist-dev-da28c',
    storageBucket: 'shoplist-dev-da28c.firebasestorage.app',
    iosBundleId: 'com.example.shoplist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2AfnZv1krjYwLpRC8YZa1WtvxnjPgNOU',
    appId: '1:385557618478:web:e86d81048eb052dbee64bf',
    messagingSenderId: '385557618478',
    projectId: 'shoplist-dev-da28c',
    authDomain: 'shoplist-dev-da28c.firebaseapp.com',
    storageBucket: 'shoplist-dev-da28c.firebasestorage.app',
    measurementId: 'G-3SNQH4DDKN',
  );
}